title: Forlaget Sidste Århundrede
email: redaktion@sidsteaarhundrede.dk
description: Forlaget Sidste Århundrede er stiftet med det formål at udgive overset litteratur i dansk oversættelse. Vi interesserer os især for det excentriske, det monomane, det ekspressionistiske og det groteske.
baseurl: ""
url: "localhost"

markdown: kramdown
